name: Auto test
on: push
jobs:
  run-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use pnpm@7
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js@16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Start lint
        run: pnpm jest
